language: node_js
node_js:
  - "11.0"

cache:
  yarn: true
  directories:
    - ./node_modules
branches:
  only:
    - master
sudo: required
before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.5.1-1
addons:
  chrome: stable
before_script:
  - yarn add -g @vue/cli
  - - yarn add -g firebase-tools
script:
  - yarn install
  - yarn run build

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: HfHXgtDDnq7lbYafGexOz6NzxLk6JfeYth138GZsu5YXeWj0xkrKk6mrmVgTZfOKSzQ7fiaO0WdNrxRlQoJByW4GNzaHC9S5WNN9ySNdn8ySgvH7dX7ijAYyWHHduycHTB5QBVp8y3k7VAwooJ1X7gLmDqNvY5Yy042KbVzKMJAQxDe42UkF8uXhKINAxBLmMfcGzTHFR6Zq2g1J0irCXKb4pmxHOWkeNdmQFO0dY25ElLBxZp3BSC3/Qy+EFMHfaoE7/NIKQGE4Ump31N095jNaNkZTR5T44x+QldpYgQNMgRRmi29ptC1C/mDlsIlsLzSyxWw0QLOqnnejUY4rRaUuDba5jxJS++vgat8uRRe1ZmQBr63d9db7Xr6HkcEen0pFsY3sy3oZIQPIZlEVXtC8V5Fla7WUsWURJTOxvlhGxsRxngow7BJL2FQFr8Gs209Z0FVZXbhE5vjtEU7p9zcxGEnsobhmgwvAVJcoP52yoEs+6vCw0p2ZcQ6Hj5JBniPjzI7GYAcSzDfGQEW6nqSh3UeDuYgBN4XY2s8RkA6HbLtMfqbdLElvVebQlPlcA8vCFV+GxewkoPlOgVCE15xRUU5OYzVdJRywTndGZh6jY6ub2s4ZgyJDsXKHeluUGXuDGlKL9rLT5G2RL7dY6ylrfk+zlOUYXIMTrmvLTG8=
