dist: trusty
env:
  matrix:
  - NODE_ENV=production
  global:
  - secure: VDWkRroaPFsZSa6EQRlSEXuIP5+vvgfwiJPUnZDAsYlfZRIWtF+5qA0Y3aHS0oXj7IA9vztAeuh1bmMddbdst5U4oWc3+fOHuA8VlC9QtjzOulJYTwdJIdHUMPzzXF+svHQ988ZfZ23KS7/euXc/f4e/ikB5QTOkkiHU4UNr1YlNwXrqOWx176/smydE1sGDDM1sfw0ZKkt0EhxIeh1P3phRJG2IOm2xbYl+pKPwy603eHdTIbvO5rdde/SelOvXaO7eQ+etdjSyzY9WoE+G1tJwxqf2ZSMLrj3M1ISIMGVk1wG6Dee82oy63Dk3LY4jMtYiMohgLAk3No4FhktZeajxz+XdRTG6VnYOJ4KbPQn48Nk3Qqlmn4gG5vOpZEwxfgTS/TmyhsqQqo17/wYx+4AKCFVtpWxQ4RWNg0q8Y+iUwwK+31Q4EOQNr1Ltbni2pI/+XH6hUoR5hk8JVHRx7HqyVAcPZea0LbhjTukL6CcHYCnc5anQlD8kOS9FxBPc2vvbWySAzOkVrLRmJ92r5jYMGwUl1voQrsJD4RzHPOH1GH0CZMfm+DElxwdBV5hLY33cxK2ZwNaxG6S8eWJ898WcTVnqRSV593F619C/CCqiu+oIvaUa4X507rLqPJQSkz9CkuAb1MOxpO1uy7Kxvlp6THbQcSEdh8oayGEfyi0=
  - secure: Z8AImS1HAOyiwc387EsZJNnY3nGB8YA7FEyelqa0rvTvGDlUyLVgaZAvVegNFLiy7Bj5R0vO8W3EPc7iOcpe5ndS20JBbpY5TzdDjjQeD2V/IJjEO8UN9YAqy8LqU9TnuJNXhi/nYhHqXwOeg1rIwBHj3hlQyDEiY4zHlTMiVE/m27xzfQStqg6gJYZOnMnyWGqK9v4kImMBkhZY3HHZodHt3ise5IHgxc+flhESDh85GJ8EeGBoNn4s3W9nHECaC3HF9UXT5AriokSouDYgSeXk85Hlzlmey/Xw08GH/pTjWRHg8QY1EMTTY2ZLtDbgRBP9dVy//C5+2P8hw2RlWoSi8Wv2WHoFkj0woFrroGLwyY2PhJUEnwCWS7/KziNwzxZQlp6OqjwyN7Ff+kq4D7ZmjatJQN2HmVtn4NRAUPGNO80ba3S7V+BDEkMEKNsXuSSW6La4mPZla1/Wi0bD2m/+CGjBPNr0LLNtOhDDOBg3wRaKhWcCgKgPLUfZBqdn+JXdAJZvfYHZN74sLhPt4Z6oWki1ecqrg4pjpNc3nVZX7WwFYKpWqKiJ45Nk0+E2gHIsRtVvjFI22E7tNxJAN9jWglHHtnNVdylLH7f5rTp3j5yVofWpfbSWfP6aLxJgYNvzffx1BqESn+PJlkSwdZRutLQ9e145b8YgCllg44w=
sudo: required
before_install:
- sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update -qq
- sudo apt-get install -y -qq yarn=1.5.1-1
addons:
  chrome: stable
language: node_js
node_js:
  - "11.0"
cache:
  yarn: false
  directories:
  - "./node_modules"
install:
- yarn install

before_script:
  yarn global add @vue/cli
  yarn global add firebase-tools
script:
- xvfb-run -a yarn lint
- xvfb-run -a yarn build
deploy:
  provider: firebase
  token:
    secure: HfHXgtDDnq7lbYafGexOz6NzxLk6JfeYth138GZsu5YXeWj0xkrKk6mrmVgTZfOKSzQ7fiaO0WdNrxRlQoJByW4GNzaHC9S5WNN9ySNdn8ySgvH7dX7ijAYyWHHduycHTB5QBVp8y3k7VAwooJ1X7gLmDqNvY5Yy042KbVzKMJAQxDe42UkF8uXhKINAxBLmMfcGzTHFR6Zq2g1J0irCXKb4pmxHOWkeNdmQFO0dY25ElLBxZp3BSC3/Qy+EFMHfaoE7/NIKQGE4Ump31N095jNaNkZTR5T44x+QldpYgQNMgRRmi29ptC1C/mDlsIlsLzSyxWw0QLOqnnejUY4rRaUuDba5jxJS++vgat8uRRe1ZmQBr63d9db7Xr6HkcEen0pFsY3sy3oZIQPIZlEVXtC8V5Fla7WUsWURJTOxvlhGxsRxngow7BJL2FQFr8Gs209Z0FVZXbhE5vjtEU7p9zcxGEnsobhmgwvAVJcoP52yoEs+6vCw0p2ZcQ6Hj5JBniPjzI7GYAcSzDfGQEW6nqSh3UeDuYgBN4XY2s8RkA6HbLtMfqbdLElvVebQlPlcA8vCFV+GxewkoPlOgVCE15xRUU5OYzVdJRywTndGZh6jY6ub2s4ZgyJDsXKHeluUGXuDGlKL9rLT5G2RL7dY6ylrfk+zlOUYXIMTrmvLTG8=
after_script:
- pkill node
notifications:
  email: false
